[book]
authors = ["nxe"]
language = "en"
multilingual = false
src = "src"
title = "lineas"

[build]
build-dir = "../web/book"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/RosiePuddles/lineas/tree/master/book"

[output.html.playground]
runnable = false
